"""Add security fields and audit logging

Revision ID: 081bb3e45f68
Revises: ef4f3a050f56
Create Date: 2025-08-04 11:04:11.680855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081bb3e45f68'
down_revision: Union[str, None] = 'ef4f3a050f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_config_key'), ['key'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_chat_created', ['chat_id', 'created_at'], unique=False)
        batch_op.create_index('idx_messages_deleted', ['is_deleted'], unique=False)
        batch_op.create_index('idx_messages_recipient_created', ['recipient_id', 'created_at'], unique=False)
        batch_op.create_index('idx_messages_sender_created', ['sender_id', 'created_at'], unique=False)
        batch_op.create_index('idx_messages_status', ['status'], unique=False)
        batch_op.create_index('idx_messages_type_created', ['message_type', 'created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_password_change', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_notifications', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_users_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_users_email_active', ['email', 'is_active'], unique=False)
        batch_op.create_index('idx_users_failed_attempts', ['failed_login_attempts'], unique=False)
        batch_op.create_index('idx_users_locked_until', ['locked_until'], unique=False)
        batch_op.create_index('idx_users_role_active', ['role', 'is_active'], unique=False)
        batch_op.create_index('idx_users_status_last_seen', ['status', 'last_seen'], unique=False)
        batch_op.create_index('idx_users_username_active', ['username', 'is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_username_active')
        batch_op.drop_index('idx_users_status_last_seen')
        batch_op.drop_index('idx_users_role_active')
        batch_op.drop_index('idx_users_locked_until')
        batch_op.drop_index('idx_users_failed_attempts')
        batch_op.drop_index('idx_users_email_active')
        batch_op.drop_index('idx_users_created_at')
        batch_op.drop_column('push_notifications')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('last_password_change')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('salt')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_type_created')
        batch_op.drop_index('idx_messages_status')
        batch_op.drop_index('idx_messages_sender_created')
        batch_op.drop_index('idx_messages_recipient_created')
        batch_op.drop_index('idx_messages_deleted')
        batch_op.drop_index('idx_messages_chat_created')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_config_key'))

    op.drop_table('app_config')
    # ### end Alembic commands ###
